---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::<acc-id>:role/prometheus"
  # we use iam role for this service acconut to grant access to s3 bucket